export const contentCategories = {
  image: [
    "image/jpeg",
    "image/png",
    ".image/gif",
    "image/bmp",
    "image/svg+xml",
    "image/webp",
    "image/x-icon",
    "image/tiff",
  ],
  video: [
    "video/mp4",
    "video/avi",
    "video/quicktime",
    "video/x-ms-wmv",
    "video/x-flv",
    "video/webm",
    "video/x-matroska",
    "video",
  ],
  audio: [
    "audio/mpeg",
    "audio/wav",
    "audio/flac",
    "audio/aac",
    "audio/ogg",
    "audio/x-ms-wma",
    "audio/mp4",
  ],
  document: [
    "application/pdf",
    "application/msword",
    "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
    "text/plain",
    "application/rtf",
  ],
  code: [
    "text/javascript",
    "text/html",
    "text/css",
    "text/x-python",
    "text/x-java-source",
    "text/x-c++src",
    "text/x-c",
    "application/x-httpd-php",
  ],
};
